name: doorr
description: "Prowlarr frontend for Android"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/lang.json

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http_mock_adapter: ^0.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
